<?php
/**
 * BuyerTaxInformation
 *
 * PHP version 5
 *
 * @category Class
 * @package  B1\AmazonSPAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace B1\AmazonSPAPI\Model;

use \ArrayAccess;
use \B1\AmazonSPAPI\ObjectSerializer;

/**
 * BuyerTaxInformation Class Doc Comment
 *
 * @category Class
 * @description Contains the business invoice tax information.
 * @package  B1\AmazonSPAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class BuyerTaxInformation implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'BuyerTaxInformation';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'buyerLegalCompanyName' => 'string',
        'buyerBusinessAddress' => 'string',
        'buyerTaxRegistrationId' => 'string',
        'buyerTaxOffice' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'buyerLegalCompanyName' => null,
        'buyerBusinessAddress' => null,
        'buyerTaxRegistrationId' => null,
        'buyerTaxOffice' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'buyerLegalCompanyName' => 'BuyerLegalCompanyName',
        'buyerBusinessAddress' => 'BuyerBusinessAddress',
        'buyerTaxRegistrationId' => 'BuyerTaxRegistrationId',
        'buyerTaxOffice' => 'BuyerTaxOffice'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'buyerLegalCompanyName' => 'setBuyerLegalCompanyName',
        'buyerBusinessAddress' => 'setBuyerBusinessAddress',
        'buyerTaxRegistrationId' => 'setBuyerTaxRegistrationId',
        'buyerTaxOffice' => 'setBuyerTaxOffice'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'buyerLegalCompanyName' => 'getBuyerLegalCompanyName',
        'buyerBusinessAddress' => 'getBuyerBusinessAddress',
        'buyerTaxRegistrationId' => 'getBuyerTaxRegistrationId',
        'buyerTaxOffice' => 'getBuyerTaxOffice'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['buyerLegalCompanyName'] = isset($data['buyerLegalCompanyName']) ? $data['buyerLegalCompanyName'] : null;
        $this->container['buyerBusinessAddress'] = isset($data['buyerBusinessAddress']) ? $data['buyerBusinessAddress'] : null;
        $this->container['buyerTaxRegistrationId'] = isset($data['buyerTaxRegistrationId']) ? $data['buyerTaxRegistrationId'] : null;
        $this->container['buyerTaxOffice'] = isset($data['buyerTaxOffice']) ? $data['buyerTaxOffice'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets buyerLegalCompanyName
     *
     * @return string
     */
    public function getBuyerLegalCompanyName()
    {
        return $this->container['buyerLegalCompanyName'];
    }

    /**
     * Sets buyerLegalCompanyName
     *
     * @param string $buyerLegalCompanyName Business buyer's company legal name.
     *
     * @return $this
     */
    public function setBuyerLegalCompanyName($buyerLegalCompanyName)
    {
        $this->container['buyerLegalCompanyName'] = $buyerLegalCompanyName;

        return $this;
    }

    /**
     * Gets buyerBusinessAddress
     *
     * @return string
     */
    public function getBuyerBusinessAddress()
    {
        return $this->container['buyerBusinessAddress'];
    }

    /**
     * Sets buyerBusinessAddress
     *
     * @param string $buyerBusinessAddress Business buyer's address.
     *
     * @return $this
     */
    public function setBuyerBusinessAddress($buyerBusinessAddress)
    {
        $this->container['buyerBusinessAddress'] = $buyerBusinessAddress;

        return $this;
    }

    /**
     * Gets buyerTaxRegistrationId
     *
     * @return string
     */
    public function getBuyerTaxRegistrationId()
    {
        return $this->container['buyerTaxRegistrationId'];
    }

    /**
     * Sets buyerTaxRegistrationId
     *
     * @param string $buyerTaxRegistrationId Business buyer's tax registration ID.
     *
     * @return $this
     */
    public function setBuyerTaxRegistrationId($buyerTaxRegistrationId)
    {
        $this->container['buyerTaxRegistrationId'] = $buyerTaxRegistrationId;

        return $this;
    }

    /**
     * Gets buyerTaxOffice
     *
     * @return string
     */
    public function getBuyerTaxOffice()
    {
        return $this->container['buyerTaxOffice'];
    }

    /**
     * Sets buyerTaxOffice
     *
     * @param string $buyerTaxOffice Business buyer's tax office.
     *
     * @return $this
     */
    public function setBuyerTaxOffice($buyerTaxOffice)
    {
        $this->container['buyerTaxOffice'] = $buyerTaxOffice;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


