<?php
/**
 * BuyerTaxInformationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  B1\AmazonSPAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace B1\AmazonSPAPI;

/**
 * BuyerTaxInformationTest Class Doc Comment
 *
 * @category    Class
 * @description Contains the business invoice tax information.
 * @package     B1\AmazonSPAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BuyerTaxInformationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "BuyerTaxInformation"
     */
    public function testBuyerTaxInformation()
    {
    }

    /**
     * Test attribute "buyerLegalCompanyName"
     */
    public function testPropertyBuyerLegalCompanyName()
    {
    }

    /**
     * Test attribute "buyerBusinessAddress"
     */
    public function testPropertyBuyerBusinessAddress()
    {
    }

    /**
     * Test attribute "buyerTaxRegistrationId"
     */
    public function testPropertyBuyerTaxRegistrationId()
    {
    }

    /**
     * Test attribute "buyerTaxOffice"
     */
    public function testPropertyBuyerTaxOffice()
    {
    }
}
