<?php
/**
 * CreateShipmentRequestTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  B1\AmazonSPAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Merchant Fulfillment
 *
 * The Selling Partner API for Merchant Fulfillment helps you build applications that let sellers purchase shipping for non-Prime and Prime orders using Amazon’s Buy Shipping Services.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace B1\AmazonSPAPI;

/**
 * CreateShipmentRequestTest Class Doc Comment
 *
 * @category    Class
 * @description Request schema.
 * @package     B1\AmazonSPAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateShipmentRequestTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateShipmentRequest"
     */
    public function testCreateShipmentRequest()
    {
    }

    /**
     * Test attribute "shipmentRequestDetails"
     */
    public function testPropertyShipmentRequestDetails()
    {
    }

    /**
     * Test attribute "shippingServiceId"
     */
    public function testPropertyShippingServiceId()
    {
    }

    /**
     * Test attribute "shippingServiceOfferId"
     */
    public function testPropertyShippingServiceOfferId()
    {
    }

    /**
     * Test attribute "hazmatType"
     */
    public function testPropertyHazmatType()
    {
    }

    /**
     * Test attribute "labelFormatOption"
     */
    public function testPropertyLabelFormatOption()
    {
    }

    /**
     * Test attribute "shipmentLevelSellerInputsList"
     */
    public function testPropertyShipmentLevelSellerInputsList()
    {
    }
}
