<?php
/**
 * CreateReportScheduleSpecificationTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  B1\AmazonSPAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2021-06-30
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace B1\AmazonSPAPI;

/**
 * CreateReportScheduleSpecificationTest Class Doc Comment
 *
 * @category    Class
 * @description CreateReportScheduleSpecification
 * @package     B1\AmazonSPAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class CreateReportScheduleSpecificationTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "CreateReportScheduleSpecification"
     */
    public function testCreateReportScheduleSpecification()
    {
    }

    /**
     * Test attribute "reportType"
     */
    public function testPropertyReportType()
    {
    }

    /**
     * Test attribute "marketplaceIds"
     */
    public function testPropertyMarketplaceIds()
    {
    }

    /**
     * Test attribute "reportOptions"
     */
    public function testPropertyReportOptions()
    {
    }

    /**
     * Test attribute "period"
     */
    public function testPropertyPeriod()
    {
    }

    /**
     * Test attribute "nextReportCreationTime"
     */
    public function testPropertyNextReportCreationTime()
    {
    }
}
