<?php
/**
 * InventoryDetailsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  B1\AmazonSPAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for FBA Inventory
 *
 * The Selling Partner API for FBA Inventory lets you programmatically retrieve information about inventory in Amazon's fulfillment network. Today this API is available only in the North America region. In 2021 we plan to release this API in the Europe and Far East regions.
 *
 * OpenAPI spec version: v1
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace B1\AmazonSPAPI;

/**
 * InventoryDetailsTest Class Doc Comment
 *
 * @category    Class
 * @description Summarized inventory details. This object will not appear if the details parameter in the request is false.
 * @package     B1\AmazonSPAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class InventoryDetailsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "InventoryDetails"
     */
    public function testInventoryDetails()
    {
    }

    /**
     * Test attribute "fulfillableQuantity"
     */
    public function testPropertyFulfillableQuantity()
    {
    }

    /**
     * Test attribute "inboundWorkingQuantity"
     */
    public function testPropertyInboundWorkingQuantity()
    {
    }

    /**
     * Test attribute "inboundShippedQuantity"
     */
    public function testPropertyInboundShippedQuantity()
    {
    }

    /**
     * Test attribute "inboundReceivingQuantity"
     */
    public function testPropertyInboundReceivingQuantity()
    {
    }

    /**
     * Test attribute "reservedQuantity"
     */
    public function testPropertyReservedQuantity()
    {
    }

    /**
     * Test attribute "researchingQuantity"
     */
    public function testPropertyResearchingQuantity()
    {
    }

    /**
     * Test attribute "unfulfillableQuantity"
     */
    public function testPropertyUnfulfillableQuantity()
    {
    }
}
