<?php
/**
 * ItemBuyerInfoTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  B1\AmazonSPAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Orders
 *
 * The Selling Partner API for Orders helps you programmatically retrieve order information. These APIs let you develop fast, flexible, custom applications in areas like order synchronization, order research, and demand-based decision support tools.
 *
 * OpenAPI spec version: v0
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace B1\AmazonSPAPI;

/**
 * ItemBuyerInfoTest Class Doc Comment
 *
 * @category    Class
 * @description A single item&#39;s buyer information.
 * @package     B1\AmazonSPAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ItemBuyerInfoTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ItemBuyerInfo"
     */
    public function testItemBuyerInfo()
    {
    }

    /**
     * Test attribute "buyerCustomizedInfo"
     */
    public function testPropertyBuyerCustomizedInfo()
    {
    }

    /**
     * Test attribute "giftWrapPrice"
     */
    public function testPropertyGiftWrapPrice()
    {
    }

    /**
     * Test attribute "giftWrapTax"
     */
    public function testPropertyGiftWrapTax()
    {
    }

    /**
     * Test attribute "giftMessageText"
     */
    public function testPropertyGiftMessageText()
    {
    }

    /**
     * Test attribute "giftWrapLevel"
     */
    public function testPropertyGiftWrapLevel()
    {
    }
}
