<?php
/**
 * ReportTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  B1\AmazonSPAPI
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Selling Partner API for Reports
 *
 * The Selling Partner API for Reports lets you retrieve and manage a variety of reports that can help selling partners manage their businesses.
 *
 * OpenAPI spec version: 2021-06-30
 * 
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.25
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace B1\AmazonSPAPI;

/**
 * ReportTest Class Doc Comment
 *
 * @category    Class
 * @description Detailed information about the report.
 * @package     B1\AmazonSPAPI
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ReportTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Report"
     */
    public function testReport()
    {
    }

    /**
     * Test attribute "marketplaceIds"
     */
    public function testPropertyMarketplaceIds()
    {
    }

    /**
     * Test attribute "reportId"
     */
    public function testPropertyReportId()
    {
    }

    /**
     * Test attribute "reportType"
     */
    public function testPropertyReportType()
    {
    }

    /**
     * Test attribute "dataStartTime"
     */
    public function testPropertyDataStartTime()
    {
    }

    /**
     * Test attribute "dataEndTime"
     */
    public function testPropertyDataEndTime()
    {
    }

    /**
     * Test attribute "reportScheduleId"
     */
    public function testPropertyReportScheduleId()
    {
    }

    /**
     * Test attribute "createdTime"
     */
    public function testPropertyCreatedTime()
    {
    }

    /**
     * Test attribute "processingStatus"
     */
    public function testPropertyProcessingStatus()
    {
    }

    /**
     * Test attribute "processingStartTime"
     */
    public function testPropertyProcessingStartTime()
    {
    }

    /**
     * Test attribute "processingEndTime"
     */
    public function testPropertyProcessingEndTime()
    {
    }

    /**
     * Test attribute "reportDocumentId"
     */
    public function testPropertyReportDocumentId()
    {
    }
}
